version: '3'

services:
  app:
    image: rafaelmendes01/teste-front:0.1.0  
    ports:
      - 80:80
    container_name: ngnix-front
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    networks:
      - nginx
networks:
  nginx:
    driver: bridge